{{&makefile_descriptor}}
NAME = {{filename}}
CC = gcc
CFLAGS = -Wall -O2 -Werror -Wmissing-noreturn -Wpacked -Wunreachable-code
HEAD = {{filename}}.h
SOURCES = {{filename}}.c main.c
OBJ = $(SOURCES:.c=.o)

.PHONY : clean help install uninstall

%.o: %.c $(HEAD)
	@$(CC) $(CFLAGS) -c $< -o $@ 

build: $(NAME)

$(NAME): $(OBJ)
	@$(CC) $(CFLAGS) -o $@ $^
	@echo " "
	@echo $(OBJ) "compiled successfully!"
	@echo $(NAME) "was generated for illustrative purposes"
	@echo " "
	@echo "Edit 'main.c' file and compile again if you want to try to interact with the generated functions."

install:
	-@cp ./$(OBJ) /usr/bin
	@echo $(OBJ) "installed in /usr/bin"

uninstall:
	-@rm /usr/bin/$(OBJ)
	@echo $(OBJ) "uninstalled from /usr/bin"

clean:
	@echo $(OBJ) "removed successfully!"

help:
	@echo
	@echo "Makefile"
	@echo
	@echo "make/make build  : build all"
	@echo "install          : install tool in the system. Root permission required"
	@echo "uninstall        : remove tool from system. Root permission required"
	@echo "clean            : remove all .o files and executable file"
	@echo "NAME=yourname    : change program name"
	@echo
	@echo  "-------------------------------------------------------------"
	@echo  "  Makefile generated using PVSio-web MisraCPrinter ver 0.1"
	@echo  "  Tool freely available at http:##www.pvsioweb.org"
	@echo  "-------------------------------------------------------------" 
	@echo

{{&makefile_disclaimer}}
