{{&makefile_descriptor}}
NAME = main
CC = gcc
CFLAGS = -Wall -O2 -Werror -Wmissing-noreturn -Wpacked -Wunreachable-code
DEBUG = -Wall -O2 -Werror -Wmissing-noreturn -Wpacked -Wunreachable-code -D DEBUG
HEAD = {{filename}}.h
SOURCES = {{filename}}.c main.c
OBJ = $(SOURCES:.c=.o)
DEBUGFILES = main.dSYM

.PHONY : clean help install uninstall

%.o: %.c $(HEAD)
	@$(CC) $(CFLAGS) -c $< -o $@ 

build: $(NAME)

debug:$(OBJ)
	@$(CC) $(DEBUG) -g $(SOURCES) -o $(NAME)
	-@rm -r main.o
	@echo " "
	@echo $(OBJ) "compiled successfully in debug mode"
	@echo "executable file (main) was generated for illustrative purposes"
	
$(NAME): $(OBJ)
	@$(CC) $(CFLAGS) -o $@ $^
	-@rm -r main.o
	@echo " "
	@echo $(OBJ) "compiled successfully!"
	@echo "executable file (main) was generated for illustrative purposes"
	@echo " "
	@echo "Edit 'main.c' file and compile again if you want to try to interact with the generated functions."

install:
	-@cp ./$(OBJ) /usr/bin
	@echo $(OBJ) "installed in /usr/bin"

uninstall:
	-@rm /usr/bin/$(OBJ)
	@echo $(OBJ) "uninstalled from /usr/bin"

clean:
	-@rm -f -r ./*.o $(NAME) $(DEBUGFILES)
	@echo $(OBJ) "removed successfully!"

help:
	@echo
	@echo "Makefile"
	@echo
	@echo "make/make build  : build all"
	@echo "debug 			: enable and compile in debug mode"
	@echo "install          : install tool in the system. Root permission required"
	@echo "uninstall        : remove tool from system. Root permission required"
	@echo "clean            : remove all .o files and executable file"
	@echo "NAME=yourname    : change program name, default is: 'main' "
	@echo
	@echo  "-------------------------------------------------------------"
	@echo  "  Makefile generated using PVSio-web MisraCPrinter ver 0.1"
	@echo  "  Tool freely available at http:##www.pvsioweb.org"
	@echo  "-------------------------------------------------------------" 
	@echo

{{&makefile_disclaimer}}
